DROP TABLE IF EXISTS STOCK_DETAILS;
  
CREATE TABLE STOCK_DETAILS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  currentPrice NUMERIC(15,5) NOT NULL,
  lastUpdated TIMESTAMP NOT NULL
);