global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring_boot_application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']